name: Container action hello workflow
run-name: Container action hello workflow
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: Choose a runner set on which to run this workflow.
        options:
          - runner-set
          - runner-set-k8s
          - runner-set-dind-rootful
          - runner-set-dind-rootless
      wait:
        description: Wait after attempting to execute container action?
        type: boolean

jobs:
  container-action-hello-job:
    runs-on: ${{ github.event.inputs.runs-on }}
    container:
      image: registry.access.redhat.com/ubi10/ubi:latest
      env:
        MY_VAR: foo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run container action
        uses: ./hello-world-container-action
      - name: Wait for 600 seconds
        if: ${{ github.event.inputs.wait == 'true' }}
        run: |
          sleep 600
