name: Simple long workflow
run-name: Simple long workflow
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: Choose a runner set on which to run this workflow.
        options:
          - runner-set
          - runner-set-k8s
          - runner-set-dind-rootful
          - runner-set-dind-rootless
jobs:
  simple-long-job:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted outside of GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Get hostname and runner details
        run: |
          set -x
          hostname
          uname -a
          cat /etc/os-release
      - name: Wait for 600 seconds
        run: |
          sleep 600
      - run: echo "🍏 This job's status is ${{ job.status }}."
